if(${PORT} MATCHES "soundtouch")
	set(VCPKG_LIBRARY_LINKAGE dynamic)
else()
	set(VCPKG_LIBRARY_LINKAGE static)
endif()

set(VCPKG_ENV_PASSTHROUGH_UNTRACKED "LLVM_PATH;LLVMInstallDir")
set(VCPKG_ENV_PASSTHROUGH "CC;CXX")
