if(NOT _VCPKG_WINDOWS_TOOLCHAIN)
    set(_VCPKG_WINDOWS_TOOLCHAIN 1)
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>$<$<STREQUAL:${VCPKG_CRT_LINKAGE},dynamic>:DLL>" CACHE STRING "")
    set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "")

    if(POLICY CMP0056)
        cmake_policy(SET CMP0056 NEW)
    endif()
    if(POLICY CMP0066)
        cmake_policy(SET CMP0066 NEW)
    endif()
    if(POLICY CMP0067)
        cmake_policy(SET CMP0067 NEW)
    endif()
    if(POLICY CMP0137)
        cmake_policy(SET CMP0137 NEW)
    endif()

    include("${CMAKE_CURRENT_LIST_DIR}/clang.cmake")

    set(MSVC_LIKE FALSE)
    if(MSVC OR CMAKE_CXX_COMPILER MATCHES "clang-cl.exe$" OR CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
        set(MSVC_LIKE TRUE)
    endif()

    list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
       VCPKG_CRT_LINKAGE VCPKG_TARGET_ARCHITECTURE VCPKG_SET_CHARSET_FLAG
       VCPKG_C_FLAGS VCPKG_CXX_FLAGS
       VCPKG_C_FLAGS_DEBUG VCPKG_CXX_FLAGS_DEBUG
       VCPKG_C_FLAGS_RELEASE VCPKG_CXX_FLAGS_RELEASE
       VCPKG_LINKER_FLAGS VCPKG_LINKER_FLAGS_RELEASE VCPKG_LINKER_FLAGS_DEBUG
       VCPKG_PLATFORM_TOOLSET
    )

    set(CMAKE_SYSTEM_NAME Windows CACHE STRING "")

    if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
        set(CMAKE_SYSTEM_PROCESSOR x86 CACHE STRING "")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
        set(CMAKE_SYSTEM_PROCESSOR AMD64 CACHE STRING "")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm")
        set(CMAKE_SYSTEM_PROCESSOR ARM CACHE STRING "")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64")
        set(CMAKE_SYSTEM_PROCESSOR ARM64 CACHE STRING "")
    endif()

    if(DEFINED VCPKG_CMAKE_SYSTEM_VERSION)
        set(CMAKE_SYSTEM_VERSION "${VCPKG_CMAKE_SYSTEM_VERSION}" CACHE STRING "" FORCE)
    endif()

    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
        if(CMAKE_SYSTEM_PROCESSOR STREQUAL CMAKE_HOST_SYSTEM_PROCESSOR)
            set(CMAKE_CROSSCOMPILING OFF CACHE STRING "")
        elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86")
            # any of the four platforms can run x86 binaries
            set(CMAKE_CROSSCOMPILING OFF CACHE STRING "")
        elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "ARM64")
            # arm64 can run binaries of any of the four platforms after Windows 11
            set(CMAKE_CROSSCOMPILING OFF CACHE STRING "")
        endif()

        if(NOT DEFINED CMAKE_SYSTEM_VERSION)
            set(CMAKE_SYSTEM_VERSION "${CMAKE_HOST_SYSTEM_VERSION}" CACHE STRING "")
        endif()
    endif()

     if(VCPKG_CRT_LINKAGE STREQUAL "dynamic")
        if(MSVC_LIKE)
            set(VCPKG_CRT_LINK_FLAG_DEBUG " /MDd")
            set(VCPKG_CRT_LINK_FLAG_RELEASE " /MD")
        else()
            set(VCPKG_CRT_LINK_FLAG_DEBUG " -fms-runtime-lib=dll_dbg")
            set(VCPKG_CRT_LINK_FLAG_RELEASE " -fms-runtime-lib=dll")
        endif()
    elseif(VCPKG_CRT_LINKAGE STREQUAL "static")
        if(MSVC_LIKE)
            set(VCPKG_CRT_LINK_FLAG_DEBUG " /MTd")
            set(VCPKG_CRT_LINK_FLAG_RELEASE " /MT")
        else()
            set(VCPKG_CRT_LINK_FLAG_DEBUG " -fms-runtime-lib=static_dbg")
            set(VCPKG_CRT_LINK_FLAG_RELEASE " -fms-runtime-lib=static")
        endif()
    else()
        message(FATAL_ERROR "Invalid setting for VCPKG_CRT_LINKAGE: \"${VCPKG_CRT_LINKAGE}\". It must be \"static\" or \"dynamic\"")
    endif()

    if(MSVC_LIKE)
        set(CHARSET_FLAG "/utf-8")
        if (NOT VCPKG_SET_CHARSET_FLAG OR VCPKG_PLATFORM_TOOLSET MATCHES "v120")
            # VS 2013 does not support /utf-8
            set(CHARSET_FLAG "")
        endif()
    else()
        # Standard Clang uses GCC-style charset flag
        set(CHARSET_FLAG "-finput-charset=UTF-8 -fexec-charset=UTF-8")
    endif()

    set(MP_BUILD_FLAG "")
    if(MSVC_LIKE)
        set(MP_BUILD_FLAG "/MP ")
    endif()

    # Set base compiler flags
    if(MSVC_LIKE)
        # MSVC-style flags
        set(CMAKE_CXX_FLAGS " /nologo /DWIN32 /D_WINDOWS ${CHARSET_FLAG} /GR /EHsc ${MP_BUILD_FLAG}${VCPKG_CXX_FLAGS}" CACHE STRING "")
        set(CMAKE_C_FLAGS " /nologo /DWIN32 /D_WINDOWS ${CHARSET_FLAG} ${MP_BUILD_FLAG}${VCPKG_C_FLAGS}" CACHE STRING "")
    else()
        # GCC-style flags
        set(CMAKE_CXX_FLAGS " -DWIN32 -D_WINDOWS ${CHARSET_FLAG} ${MP_BUILD_FLAG}${VCPKG_CXX_FLAGS}" CACHE STRING "")
        set(CMAKE_C_FLAGS " -DWIN32 -D_WINDOWS ${CHARSET_FLAG} ${MP_BUILD_FLAG}${VCPKG_C_FLAGS}" CACHE STRING "")
    endif()

    if(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64ec")
        if(MSVC_LIKE)
            string(APPEND CMAKE_CXX_FLAGS " /arm64EC /D_AMD64_ /DAMD64 /D_ARM64EC_ /DARM64EC")
            string(APPEND CMAKE_C_FLAGS " /arm64EC /D_AMD64_ /DAMD64 /D_ARM64EC_ /DARM64EC")
        else()
            string(APPEND CMAKE_CXX_FLAGS " -march=arm64ec -D_AMD64_ -DAMD64 -D_ARM64EC_ -DARM64EC")
            string(APPEND CMAKE_C_FLAGS " -march=arm64ec -D_AMD64_ -DAMD64 -D_ARM64EC_ -DARM64EC")
        endif()
    endif()
    if(MSVC_LIKE)
        set(CMAKE_RC_FLAGS "-c65001 /DWIN32" CACHE STRING "")
    else()
        set(CMAKE_RC_FLAGS "-c65001 -DWIN32" CACHE STRING "")
    endif()

    if(MSVC_LIKE)
        set(CMAKE_CXX_FLAGS_DEBUG "/Z7 /Ob0 /Od /RTC1 ${VCPKG_CRT_LINK_FLAG_DEBUG} ${VCPKG_CXX_FLAGS_DEBUG}" CACHE STRING "")
        set(CMAKE_C_FLAGS_DEBUG "/Z7 /Ob0 /Od /RTC1 ${VCPKG_CRT_LINK_FLAG_DEBUG} ${VCPKG_C_FLAGS_DEBUG}" CACHE STRING "")
        set(CMAKE_CXX_FLAGS_RELEASE "/O2 /Oi /Gy /DNDEBUG /Z7 ${VCPKG_CRT_LINK_FLAG_RELEASE} ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")
        set(CMAKE_C_FLAGS_RELEASE "/O2 /Oi /Gy /DNDEBUG /Z7 ${VCPKG_CRT_LINK_FLAG_RELEASE} ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")
    else()
        set(CMAKE_CXX_FLAGS_DEBUG " -g -O0 -DDEBUG ${VCPKG_CRT_LINK_FLAG_DEBUG} ${VCPKG_CXX_FLAGS_DEBUG}" CACHE STRING "")
        set(CMAKE_C_FLAGS_DEBUG " -g -O0 -DDEBUG ${VCPKG_CRT_LINK_FLAG_DEBUG} ${VCPKG_C_FLAGS_DEBUG}" CACHE STRING "")
        set(CMAKE_CXX_FLAGS_RELEASE " -O3 -DNDEBUG ${VCPKG_CRT_LINK_FLAG_RELEASE} ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")
        set(CMAKE_C_FLAGS_RELEASE " -O3 -DNDEBUG ${VCPKG_CRT_LINK_FLAG_RELEASE} ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")
    endif()

    if(CMAKE_LINKER MATCHES ".*lld.*" OR LLD_LINKER)
        string(APPEND CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT " ")
        set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "-Wl,--strip-all -Wl,--gc-sections ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
        set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "-Wl,--strip-all -Wl,--gc-sections ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
        set(CMAKE_EXE_LINKER_FLAGS_RELEASE "-Wl,--strip-all -Wl,--gc-sections ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")

        string(APPEND CMAKE_STATIC_LINKER_FLAGS_DEBUG_INIT " ")
        string(APPEND CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT " ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_DEBUG} ")
        string(APPEND CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT " ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_DEBUG} ")
        string(APPEND CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT " ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_DEBUG} ")
    else()
        string(APPEND CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT " /nologo ")
        set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "/nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF /LTCG ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
        set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF /LTCG ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
        set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF /LTCG ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")

        string(APPEND CMAKE_STATIC_LINKER_FLAGS_DEBUG_INIT " /nologo ")
        string(APPEND CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT " /nologo ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_DEBUG} ")
        string(APPEND CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT " /nologo ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_DEBUG} ")
        string(APPEND CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT " /nologo ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_DEBUG} ")
    endif()

    unset(CHARSET_FLAG)
    unset(MP_BUILD_FLAG)
    unset(VCPKG_CRT_LINK_FLAG_PREFIX)
    unset(MSVC_LIKE)
endif()
